// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0IH5ArQKrZihDUpsghr1UCVs3mZLBqGc',
    appId: '1:528019018949:web:2b509b2e9a711d98a84cac',
    messagingSenderId: '528019018949',
    projectId: 'social-media-klon',
    authDomain: 'social-media-klon.firebaseapp.com',
    storageBucket: 'social-media-klon.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8H40o62PFzqgSGiWrNOR3ehkdoHkGCIU',
    appId: '1:528019018949:android:f565edff764582bda84cac',
    messagingSenderId: '528019018949',
    projectId: 'social-media-klon',
    storageBucket: 'social-media-klon.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZZBKieJyoRDN55v7YR4V0BI7EsGu_s6s',
    appId: '1:528019018949:ios:976f147f0168e7a5a84cac',
    messagingSenderId: '528019018949',
    projectId: 'social-media-klon',
    storageBucket: 'social-media-klon.appspot.com',
    iosClientId: '528019018949-53sc58n8vq1i378gnag7dskr3mpj4s8i.apps.googleusercontent.com',
    iosBundleId: 'com.example.socialMediaClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZZBKieJyoRDN55v7YR4V0BI7EsGu_s6s',
    appId: '1:528019018949:ios:976f147f0168e7a5a84cac',
    messagingSenderId: '528019018949',
    projectId: 'social-media-klon',
    storageBucket: 'social-media-klon.appspot.com',
    iosClientId: '528019018949-53sc58n8vq1i378gnag7dskr3mpj4s8i.apps.googleusercontent.com',
    iosBundleId: 'com.example.socialMediaClone',
  );
}
